config/routes.rb
Rails.application.routes.draw do
  resources :charges
  devise_for :users
  root 'rand#home'
  get 'charges/new'
  get 'charges/create'
  get 'rand/_active'
  get 'rand/_logout'
  get 'rand/_scan'
  get 'rand/_help'
  get 'rand/_nav'
  get 'rand/_search'
  get 'rand/home'
  get 'rand/_notifications'
  get 'rand/_settings'
  get 'rand/_incomplete'
  get 'rand/_profile'
  get 'rand/_invite'
  get 'rand/_purchases'
  get 'rand/_transfer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


  def new
    @amount = 100


  end

  def create
    # Amount in cents
    @amount = 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/rand_controller.rb
class RandController < ApplicationController
  before_action :authenticate_user!

  def home
  end

  def sign_in
  end

  def _active
  end

  def _profile
  end

  def _logout
  end

  def _search
  end

  def _scan
  end

  def _invite
  end

  def _transfer
  end

  def _purchases
  end

  def _notifications
  end

  def _incomplete
  end

  def _help
  end

  def _settings
  end

  def _nav
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/rand_helper.rb
module RandHelper
end

app/views/charges/create.html.erb
<h2><strong> <% @amount/100 %> USD of worth of Rand has been added to your online account</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $<span id="decamt"><%= @amount %></span>    </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="One usd's worth of rand"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>


<script>
document.getElementById("decamt").innerHTML = parseInt(document.getElementById("decamt").innerHTML/100).toFixed(2);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rando1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/rand/_help.html.erb
<%= link_to "back", :back %>

<p>Browse our FAQs</p>
<p>Contact Us</p>
<p>My Support Tickets</p>

app/views/rand/_incomplete.html.erb
<%= link_to "back", :back %>
<button id="request" onclick="requestFun()">Requests</button>
<button id="payment" onclick="'payFun()'">Payments</button>
<span id="body">
</span>

<script>
function requestFun(){
  document.getElementbyID("body").innerHTML
  //     1. on click of requests, show
  // <h3>Requests From You</h3>
  // <p>"See your requests for your money here while they're awaiting approval"</p>
  //

}
    // 2. on click of Payments show
    // <h3>Payment Invites</h3>
    // <p>"Invite people to Rando by sending money to their phone or email. Review your invitations here"</p>
    // <button>"Send A Payment" </button>

</script>

app/views/rand/_invite.html.erb
<%= link_to "back", :back %>
<h1> Invite Friends</h1>
<br />
Type in a friend's name here

The list below will show a list of the device's phone contacts and email contacts.

<!--
create functions for the above functionality
-->

app/views/rand/_logout.html.erb
<h1>Rando#_logout</h1>
<p>Find me in app/views/rando/_logout.html.erb</p>
<%= link_to "back", :back %>

app/views/rand/_nav.html.erb
<h1>Rando#_nav</h1>
<p>Find me in app/views/rando/_nav.html.erb</p>
<%= link_to "back", :back %>
<!-- idk if i even need the below line but whatever -->
<%= link_to "Start Payment", :back %>

app/views/rand/_notifications.html.erb
<%= link_to "back", :back %>

<span id="notificaion_body">
  <h3> No Notifications</h3>
  <p> You can find things that require your attention here</p>
</span>
<script>
function view_for_zero_or_more_notifications(){

}


</script>

app/views/rand/_profile.html.erb
<%= link_to "back", :back %>

<br />              image
<br />              first_name
<br />              last_name
<br />              username
<br />              email
<br />              You can be paid using your username, email, or phone number

app/views/rand/_purchases.html.erb
 <%= link_to "back", :back %>
<h1> Purchases </h1>

<p>Here is where some purchases for your money can be made.</p>

app/views/rand/_scan.html.erb
<%= link_to "back", :back %>
<h1> Code Scanner </h1>
<br />
In this page, the view;s background will be the device's camera output.
<br />
It will look for a code block that is reminiscent of a URL that resembles a Rando users' url. 

app/views/rand/_search.html.erb
<%= link_to "back", :back %>
Find someone here type to search! <input type="text"> </input>
<br />
<span id="people">A list of people will show up here
</span>

<!--  TODO: function for id: people
make the innter html of this show all friends of the user if nothing is typed in
as you type more, the search narrows down the list to the appropriate rando user-->

app/views/rand/_settings.html.erb
<%= link_to "back", :back %>
<h1>Settings</h1>
<p>Preferences:<ul>

          Edit Profile
          <ul>
<br />
                        Image
                        <br />
                        First Name
                        <br />
                        Last Name
                        <br />
                        Username
                        <br />
                        Email
                        <br />
                        You can be paid using your username, email, or phone number
        </ul>
                  Banks and Cards
           <ul>
                          Bank Accounts
                           <br />
                             #{list bank accounts}
                             <br />
                            Link Bank Accounts
                             <br />
                          Cards
                           <br />
                           #{list cards}
                           <br />
                            Add Debit or Credit Card
                             <br />
                            A standard 3% feee applies when sending money using a credit card the fee is waived for Authorized Merchant Payments, Rando balance, bank accounts, and debit cards so they are free to use.

                           </ul>

          Privacy
           <ul>
                  <b> Default Privacy Setting</b>
                   <ul>
                      Select your default privacy setting for all future payments. You can also change it for each payment individually.
                      Public: Visible to everyone
                       <br />
                      Friends: Visible to senders, recipients, and their friends
                       <br />
                      Private: visible to senders and recipients only
                     </ul>
                     <b> Past Transactions </b>
                     <ul>
                      Change the privacy setting for all previous payments and purchases. you can also go to each transaction to make individual changes
                      Limit to friends
                       <br />
                      Make all private
                     </ul>
                     <b> Friending </b>
                     <ul>
                       As your Facebook Friends and/or phone contacts join Rando you'll automatically become Rando friends.
                      Facebook_friends: on/off
                       <br />
                      Phone_contacts: on/off
                     </ul>
                   </ul>


          Blocked Users
           <ul>

                         #{blocked users}
                       </ul>
          Notifications
           <ul>
                        Push Notifications
                         <ul>
                                          Money
                                           <ul>
                                                Bank Transfer on/off
                                                 <br />
                                                Payment Received on/off
                                                 <br />
                                                Payment Sent on/off
                                                 <br />
                                                Charge request received on/off
                                                 <br />
                                                Friend Payments on/off
                                                 <br />
                                                Purchases on/off
                                               </ul>
                                          Social
                                           <ul>
                                                Likes on/off
                                                 <br />
                                                Comments on/off
                                                 <br />
                                                Friend requests on/off
                                                 <br />
                                                Mentions on/off
                                                 <br />
                                                Friends joined on/off
                                               </ul>
                                             </ul>
                        Text Notifications
                         <ul>
                                            Money
                                             <ul>
                                                  Payment received on/off
                                                   <br />
                                                  Payment sent on/off
                                                   <br />
                                                  Charge request received on/off
                                                 </ul>
                                            Social
                                             <ul>
                                                  Comments on/off
                                                   <br />
                                                  Friend requests on/off
                                                   <br />
                                                  Friend joined on/off
                                                 </ul>
                                               </ul>

                        Email Notifications
                         <ul>
                                            Security
                                             <ul>
                                                     Login Attempted on/off
                                                     <br />
                                                     Add Remembered Device on/off
                                                   </ul>
                                            Money
                                             <ul>
                                                  Payment Received on/off
                                                   <br />
                                                  Charge request received on/off
                                                   <br />
                                                  Charge request rejected on/off
                                                   <br />
                                                  Charge request canceled on/off
                                                 </ul>

                                            Social
                                             <ul>
                                                  Likes on/off
                                                   <br />
                                                  Comments on/off
                                                   <br />
                                                  Friend requests on/off
                                                   <br />
                                                  Invite reminders on/off
                                                   <br />
                                                  Friend joined on/off
                                                 </ul>
                                               </ul>
                                             </ul>

          Social Networks
           <ul>
           </ul>

          Change Phone Number
           <ul>
                              Enter your phone number. We'll send a code to make sure it's you
                               <br />
                              Put in number
                               <br />
                              By submitting, you confirm that you ar authorized to use the number entered and agree to receive SMS texts to verify you own the number. Carrier fees may apply
                             </ul>

          Emoji
           <ul>
                Suggest while typing on/off
                 <br />
                Show relevant emoji for easy access whe typing parment notes and comments
               </ul>
             </ul>
Buying: connect browsers
 <ul>
                        Connect Safari on/off
                         <br />
        Backup Payment
         <ul>
                         #{show all_backup_payments}
                         <br />
                         Add a bank or card (no purchase fees)
                       </ul>
        Connected Merchants
         <ul>
                            Connect your rando account to pay for your fabvofrite things, split purchase and share with friends.
                           </ul>
                         </ul>
Security:
 <ul>
          PIN
           <br />
          Change Password
           <ul>
                          Current?
                           <br />
                          New
                           <br />
                          Confirm
                           <br />
                          Never share your password with anyone
                         </ul>
          Remembered Devices
           <ul>
                             #{list_all_devices}
                             <br />
                             #{List this device}
                           </ul>
                         </ul>
Information:
 <ul>
            Legal
             <ul>
                   Useragreement - link
                   <br />
                   Privacy_policy - link
                   <br />
                   Licenses - link
                 </ul>
            Helpful Information
             <ul>
                                 [go crazy! updates, weblinks, you name it!]
                               </ul>
                             </ul>

Send Feedback
 <ul>
              Details
               <ul>
                Topic: [make a list of possible errors]
                 <br />
                Send Feedback
               </ul>
               Environment
               <ul>
                Current Locale
                 <br />
                Device
                 <br />
                App Name
                 <br />
                OS Version
                 <br />
                App Version
               </ul>
             </ul>

Rate Rando
   <ul>
            -link to the app store in which this is marketed in.
          </ul>

 </ul>

 Sign Out
</p>
 <br />
App Version

app/views/rand/_transfer.html.erb
<%= link_to "back", :back %>
<h1> Transfer Balance</h1>
<br />Amount to transfer:<br>
<span>##{@amount}
</span>
Your Rando Balance is $
##{@amount}

<p>Bank transfers initated before 7 pm. et on business days will typically be available in your bank account the next business day, but it can take up to 3 business days. Business days are Monday to Friday, excluding bank holidats </p>

If you have no bank or need to add a bank,
<span id="selectedBank"<%= link_to "Add card or bank"  %>
or you can view/select
<%= link_to "from all connected banks" %>



<button onclick="showStripeConfirmationTransfer()"> NEXT </button>

<script>

function showStripeConfirmationTransfer(){
  // if it's over the balance they have, issue an error
  // if it's under the balance they have, proceed,
  // proceeding is:
  // take the selected current bank from within the id="selectedBank"
  // select the amount that wants to be sent
  // take these as arguments and send those argumets into the stripe function/partial
  

}

 </script>

app/views/rand/home.html.erb
User email: <%= current_user.email %>
<br />
User id: <%= current_user.id %>

<br />

#User Image
<br />
#user Scan code
<br />
#User Full name
<%= link_to "Your Profile", rand__profile_path %>
<br />
#Username
<br />
#Amount in account.
<%= link_to "Add amount", charges_new_path %>


<br />
<br />
<%= link_to "Home", rand__active_path %>
<br />
<%= link_to "Search People", rand__search_path %>
<br />
<%= link_to "Scan Code", rand__scan_path %>
<br />
<%= link_to "Invite Friends", rand__invite_path %>
<br />
<%= link_to "Transfer to Bank", rand__transfer_path %>
<br />
<%= link_to "Purchases", rand__purchases_path %>
<br />
<%= link_to "Notifications", rand__notifications_path %>
<br />
<%= link_to "Incomplete", rand__incomplete_path %>
<br />
<%= link_to "Help", rand__help_path %>
<br />
<%= link_to "Settings", rand__settings_path %>

app/views/rand/sign_in.html.erb
<h1>Rando#sign_in</h1>
<p>Find me in app/views/rando/sign_in.html.erb</p>